export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const HOME_DATA_REQUEST = "HOME_DATA_REQUEST";
export const HOME_DATA_SUCCESS = "HOME_DATA_SUCCESS";
export const HOME_DATA_FAILURE = "HOME_DATA_FAILURE";
export const HOME_DATA_SEARCH = "HOME_DATA_SEARCH";
